name: "Archethic Web"
description: "This Github action lets you deploy any folder, file or static website to the Archethic Blockchain"
author: "Archethic Foundation"

branding:
  icon: "arrow-up-circle"
  color: "black"

inputs:
  seed: # Seed of the transaction chain
    description: "Seed of the transaction chain"
    required: true

  endpoint:
    description: "Endpoint of the network, default is https://testnet.archethic.net"
    required: true
    default: "https://testnet.archethic.net"

  path:
    description: "Path of the folder/file/website, default ./"
    required: true
    default: "./"

  keychainFundingService:
    description: "Keychain's service to funds the website transactions"

  keychainWebsiteService:
    description: "Keychain's service for the deployed website"

  sslCertificateFile:
    description: "File for the website's SSL certificate"

  sslKey:
    description: "Website's SSL key"

  sendTransactionTimeout:
    description: "Timeout for the send_transaction query (default=60000)"

  percentageOfConfirmations:
    description: "1-100 % of the confirmations success to mark the transaction as valid (default=50)"

outputs:
  transaction-address: # Url where the folder/file/website is hosted
    description: "Url where the folder/file/website is hosted"
  website_url: # Url where the folder/file/website is hosted
    description: "Url where the folder/file/website is hosted"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.seed }}
    - ${{ inputs.endpoint }}
    - ${{ inputs.path }}
    - ${{ inputs.keychainFundingService }}
    - ${{ inputs.keychainWebsiteService }}
    - ${{ inputs.sslKey }}
    - ${{ inputs.sslCertificateFile }}
    - ${{ inputs.sendTransactionTimeout}}
    - ${{ inputs.percentageOfConfirmations}}
