name: 'Deploy Folder to AEweb'
description: 'This Github action lets you deploy any folder, file or static website to AEweb'
inputs:
  seed:  # Seed of the transaction chain
    description: 'Seed of the transaction chain'
    required: true

  endpoint:
    description: 'Endpoint of the network, default is https://testnet.archethic.net'
    required: true
    default: 'https://testnet.archethic.net'

  path:
        description: 'Path of the folder/file/website, default ./'
        required: true
        default: './'

outputs:
  transaction-address: # Url where the folder/file/website is hosted
    description: 'Url where the folder/file/website is hosted'

runs:
  using: 'node18'
  main: 'index.js'
